### ISSUE TITLE
READMEのExamplesの説明を追加

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#101]
現在 v0.2.2 のREADMEにあるExampleについて、出力の説明を加えてください。

https://github.com/aki2274/KOnezumi-AID?tab=readme-ov-file#examples-1

具体的には、以下の質問が想定されますので、こちらに答えられるような説明をいれるとよいのかと思っております👀

- `gene symbol`で得られたgRNAは、`transcript ID`で得られる情報を含んでいませんが、どうしでしょうか？
- `gene symbol`で得られたgRNAはどういう基準で選ばれたのでしょうか？
- `gene symbol`で得られたgRNAの数が`transcript ID`のgRNAの数より少なくなるのはどうしでしょうか？

_Originally posted by @akikuno in https://github.com/aki2274/KOnezumi-AID/issues/96#issuecomment-2199376086_

**Comment by aki2274** [comment]
data/outputにcsvで出力されていることの記載をする．

**Comment by aki2274** [comment]
#105 で解決です．
