### ISSUE TITLE
macOS Apple Siliconにおけるインストール

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#104]
### As Is（今の状態を記載）

macOS (Apple Silicon, M1 mac mini)でテストしたところ、`conda install -c conda-forge -c bioconda konezumiaid`ではbowtieがないとエラーが出ました。
BioCondaがApple Siliconに対応していないのが原因です。

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

DAJIN2のREADMEを参考にして、macOS (Apple Silicon)用のガイドラインのご作成をお願いいたします。

https://github.com/akikuno/DAJIN2?tab=readme-ov-file#from-bioconda-recommended

### アクション（改善のための具体的なアクションを記載）

私の環境では、以下のコードでインストールが成功しました🎊

```bash
CONDA_SUBDIR=osx-64 conda create -n env-konezumiaid -c conda-forge -c bioconda python=3.10 konezumiaid -y
conda activate env-konezumiaid
conda config --env --set subdir osx-64
python -c "import platform; print(platform.machine())" 

conda install -c conda-forge -c bioconda konezumiaid -y
konezumiaid -h # OK!!!
```

### 課題 （現状分かっている課題を記載）

None

**Comment by aki2274** [comment]
> CONDA_SUBDIR=osx-64 conda create -n env-konezumiaid -c conda-forge -c bioconda python=3.10 konezumiaid -y

の行においてKOnezumiAIDをインストールしているので

> conda install -c conda-forge -c bioconda konezumiaid -y

の記載は不要でしょうか．

**Comment by akikuno** [comment]
ありがとうございます。仰るとおりですね😀
一応、確かめますね！

**Comment by akikuno** [comment]
```bash
CONDA_SUBDIR=osx-64 conda create -n test-konezumiaid -c conda-forge -c bioconda python=3.10 konezumiaid -y
conda activate test-konezumiaid
conda config --env --set subdir osx-64
```
だけで動きました🎊

```
conda install -c conda-forge -c bioconda konezumiaid -y
```
の記載は不要ですー
