### ISSUE TITLE
テストの作成

### ISSUE THREAD

**Issue by aki2274** [aki2274/KOnezumi-AID#108]
### As Is（今の状態を記載）
pytestを使ってテストを作成しているとき，2点質問が生じた．

### 疑問点
- pytestにおいて標準出力をテストする場合にはどのようにしているか．[ここ](https://qiita.com/okky_eng/items/4e4c9c3ceff4c82a22d5)を参考する以外に別のモジュール等を使われていたらご教示ください．
- 統合テストの際には予期されるエラー(使用者の入力ミス等)をテストケースに含めるべきでしょうか．

**Comment by akikuno** [comment]
## pytestにおいて標準出力をテストする場合にはどのようにしているか．[ここ](https://qiita.com/okky_eng/items/4e4c9c3ceff4c82a22d5)を参考する以外に別のモジュール等を使われていたらご教示ください．

すみません、私は標準出力はpytestではなく、bashでテストしています。

例えば私の[cstag-cli](https://github.com/akikuno/cstag-cli)では、あらかじめ期待される標準出力をテキストファイルに保存しておいて、テスト時には標準出力を適当なファイルに保存して、あらかじめ保存していたファイルとの違いがなければOK (exit 0)、あればNG (exit 1)としています。

```bash

#######################################
# From file (SAM)
#######################################

# Short format
cstag append tests/append/data/example.sam >/tmp/example_cs_short.sam

# Long format
cstag append tests/append/data/example.sam -l >/tmp/example_cs_long.sam

if ! diff /tmp/example_cs_short.sam tests/append/data/example_cs_short.sam; then
    exit 1
fi

if ! diff /tmp/example_cs_long.sam tests/append/data/example_cs_long.sam; then
    exit 1
fi

```

参考までにテストコードとGithub Actionsのyamlは以下になります。
https://github.com/akikuno/cstag-cli/blob/main/tests/append/tests.sh
https://github.com/akikuno/cstag-cli/blob/main/.github/workflows/cli-test.yml


## 統合テストの際には予期されるエラー(使用者の入力ミス等)をテストケースに含めるべきでしょうか．

はい、テストケースに含めると安心でしょう！

例えばDAJIN2では以下のように、ユーザーが空文字を送ってきたときのテストなどを用意していますー

https://github.com/akikuno/DAJIN2/blob/0c15a013e675f15743ca55a97270e8b36751567d/tests/src/utils/test_io.py#L27

**Comment by aki2274** [comment]
ご回答ありがとうございます．統合テストを行う際にこちらを参考にしてテストケースを作成させていただきます．
