### ISSUE TITLE
READMEのNOTEの削除

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#113]
無事、konezumi-aidがosx-arm64環境でインストールできるようになりました🎊🎊🎊

<img width="648" alt="image" src="https://github.com/user-attachments/assets/92565f23-a632-4317-ba48-3adfc69dea2c">

以下のREADMEのNoteが必要なくなりましたので、お手すきのときにご対応お願いしますー

![image](https://github.com/user-attachments/assets/94b596ac-b16c-4d47-970a-f7d0db62507f)

_Originally posted by @akikuno in https://github.com/aki2274/KOnezumi-AID/issues/111#issuecomment-2237792513_

**Comment by aki2274** [comment]
#116 似て解決しました．
