### ISSUE TITLE
バージョン情報の出力

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#117]
### As Is（今の状態を記載）

いま使っているkonezumiaidのバージョンを知ることができません。
利用者がどのバージョンをお使いなのかがわかるようにしたいところです👀

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

- [x] konezumiaid -v/--versionでバージョン情報を得られるようにする

### アクション（改善のための具体的なアクションを記載）

DAJIN2では、`argparse`を使って以下のようにバージョン情報を表示しています。

https://github.com/akikuno/DAJIN2/blob/5f08dce637e1081cd59099ae3b36c0e5d6bca603/src/DAJIN2/main.py#L178

バージョンはconfig.pyに記載していますが、どこでも（main.pyでも）構いません。

https://github.com/akikuno/DAJIN2/blob/5f08dce637e1081cd59099ae3b36c0e5d6bca603/src/DAJIN2/utils/config.py#L11C1-L12C1

### 課題 （現状分かっている課題を記載）

None

**Comment by aki2274** [comment]
表示できるようになったのでcloseします．
