### ISSUE TITLE
export_refflat_txt_to_csvのコードレビュー

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#19]
# `export_refflat_txt_to_csv`

拝読しました！

テストケースを作りました。
https://github.com/aki2274/KOnezumi-AID/blob/add_test_candidate_stopcodon/tests/src/test_export_refflat_txt_to_csv.py

また、コードに対するコミットはこちらになります。
https://github.com/aki2274/KOnezumi-AID/commit/abe2d61e49a3f8eff3ed1f966bcf117d0cce2ba0

以下、質問になります🙇

## export_genedata_csvは必要ですか？
こちら、csvに変換しているとのことですが、refFlatをcsvに変換する利点はあるのでしょうか？
コードを見る限り、csvに変換する、というよりも`Remove duplicates of transcriptions`のほうが重要な意味を持っているのかと思いましたが…
ご教授いただければ幸いです。

_Originally posted by @akikuno in https://github.com/aki2274/KOnezumi-AID/issues/17#issuecomment-1811771429_

**Comment by akikuno** [comment]
@aki2274 
コードの改定が進んだため、本Issueは役目を終えたのかもしれません。
こちらも一旦Closeしましょうか？

**Comment by aki2274** [comment]
承知しました。
