### ISSUE TITLE
get_cds_seq.pyのコードレビュー

### ISSUE THREAD

**Issue by aki2274** [aki2274/KOnezumi-AID#23]
[get_cds_seq.py](https://github.com/aki2274/KOnezumi-AID/blob/add_test_candidate_stopcodon/src/get_cds_seq.py)nのコードレビューをお願いします。
[testはこちらです](https://github.com/aki2274/KOnezumi-AID/blob/add_test_candidate_stopcodon/tests/src/test_get_cds_seq.py)。

get_cdsseqの関数が煩雑になってしまっているので読みにくい等あれば適宜おっしゃってください。

**Comment by akikuno** [comment]
@aki2274 
コードの改定が進んだため、本Issueはもしかしたら役目を終えたのかもしれません。
一旦Closeしましょうか？

**Comment by aki2274** [comment]
そうですね。closeします。
