### ISSUE TITLE
README.mdに使用方法を加筆

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#57]
### As Is（今の状態を記載）

README.mdを読んでも、使用方法がわからない

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

README.mdを読むと、使い方がわかるようにする

### アクション（改善のための具体的なアクションを記載）

README.mdに`Installation`、`Quick Start`を追加する

一例：https://github.com/akikuno/cstag-cli?tab=readme-ov-file#cstag-cli

### 課題 （現状分かっている課題を記載）

None

**Comment by akikuno** [comment]
@aki2274 

bedtoolsのインストールも必要ですかねー

**Comment by aki2274** [comment]
readmeの加筆が終わったのでcloseします。
