### ISSUE TITLE
Refactoringを忘れずに

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#62]
### As Is（今の状態を記載）

- 変数名の明瞭さとモジュール間の役割分担が不明瞭な印象を受けています

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

- いまのタスクが終わったら、忘れずにRefactoringのステップを踏んでください

- 変数名を明瞭にする （`data`の使用は要注意）
- 滝さんが頻繁に相互参照するモジュールがあったら、それはモジュールの[凝集度が低い](https://zenn.dev/miya_tech/articles/0dde1228045af6)ことを意味します。凝集度を高めるように、モジュールごとに明確な役割を与えましょう。

#### 変数名
- 変数名の`data`について、扶養なら削除または言い換えをする
- モジュール間で共通する変数があれば、その変数名を統一する
- 関数名にreturnされる出力の変数名があれば、その関数名とreturnの変数名は一致させる

#### モジュール
- `[generate_seq_dict_from_fasta.py](https://github.com/aki2274/KOnezumi-AID/blob/main/src/generate_seq_dict_from_fasta.py)`と`[create_gene_dataclass.py](https://github.com/aki2274/KOnezumi-AID/blob/main/src/create_gene_dataclass.py)`と`[generate_sorted_genedata_from_refflat.py](https://github.com/aki2274/KOnezumi-AID/blob/main/src/generate_sorted_genedata_from_refflat.py)`の役割分担が不明瞭な気がします （個人の感想です😂）
- `[src/convert_refflat_to_bed.py](https://github.com/aki2274/KOnezumi-AID/blob/main/src/convert_refflat_to_bed.py)`は役割としては明確ですが、単一の関数なのでモジュールとしてはややシンプルすぎるかもしれません。`converter.py`として、convertする役割を持つ関数を一挙にまとめるモジュールとしても良い気がします

### 課題 （現状分かっている課題を記載）

- None

**Comment by aki2274** [comment]
リファクタリングを進めており、必要に応じて各々のissueを立てるのでcloseします。
