### ISSUE TITLE
`nominate_candidate_stopcodon/generate_cds_seq.py`のRefactoring

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#67]
- 引数の`ds`は`transcript_records`でしょうか？
- `generate_csdseq`の、`exon_seq_to_stopcodon`を求めるコード（Line 35-48）は関数化したほうが良さそうです。コードの区切り（役割分担）が明確になると期待します。
- Line 36と38のifとelifの違いがわかりませんでした。。。コメントが両者同じ` # if stopcodon is in the last exon`であるのと、`endcodon_exon_num - ds.exonCount + 1 == 0`の意味が理解できなかったです。すみません🙇‍♀️

_Originally posted by @akikuno in https://github.com/aki2274/KOnezumi-AID/pull/66#discussion_r1581739793_

**Comment by aki2274** [comment]
PR https://github.com/aki2274/KOnezumi-AID/pull/72 での修正が行われています。
