### ISSUE TITLE
Actionsのアップグレード

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#69]
### As Is（今の状態を記載）

https://github.com/aki2274/KOnezumi-AID/blob/main/.github/workflows/pytest.yml の、`actions/checkout@v3`と`conda-incubator/setup-miniconda@v2`のバージョンが古いので、お手すきの際にアップグレードをお願いいたします。

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

`actions/checkout@v3`と`conda-incubator/setup-miniconda@v2`を`actions/checkout@v4`と`conda-incubator/setup-miniconda@v3`にアップグレードする

### アクション（改善のための具体的なアクションを記載）

上述

### 課題 （現状分かっている課題を記載）

macOSがAppele Silicon (Arm64)になり、Biocondaがそれに対応していないため、エラーが起こる可能性があります。
もしもエラーが起きた際には、macOS用のconda環境の設定が必要でして、以下をご参照いただければ幸いです。

https://github.com/akikuno/DAJIN2/actions/runs/8916876237/workflow#L36

**Comment by aki2274** [comment]
#73 でアップデートしました。
