### ISSUE TITLE
PyPIへの登録 （`updateKonezumiaidMain`ブランチのマージ後）

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#80]
### As Is（今の状態を記載）

`updateKonezumiaidMain`ブランチでのpyproject.tomlは、すでにPyPIに登録できるような形式になっております。

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

`updateKonezumiaidMain`ブランチをマージしましたら、PyPIへの登録をお願いします。

### アクション（改善のための具体的なアクションを記載）

以下の記事が参考になります。

https://qiita.com/konbraphat51/items/2bd2c5e7d1a351d82ccb

なお、Github Actionsのyamlについては上記の記事は少し古いので、最新版は以下を参考にしてください。

https://docs.github.com/ja/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

### 課題 （現状分かっている課題を記載）

None

**Comment by aki2274** [comment]
登録完了🎊
