### ISSUE TITLE
transcript nameの受付

### ISSUE THREAD

**Issue by aki2274** [aki2274/KOnezumi-AID#82]
transcript name (RefSeq id)を受け付けるが、NM_XXXX.Xのように.Xがついている場合に検索ができない問題を解決する必要がある。

**Comment by akikuno** [comment]
@aki2274 
こちら、解決しましたか？

**Comment by aki2274** [comment]
RefSeqについて学ぶ時間をとれていないので解決しておりません．
NM_XXXX.XとNM_XXXX.Yが同じであるのかなど，単純に'>'の手前をとるでよいか確認してから取り組みたいと思います．

**Comment by akikuno** [comment]
OKです！
数ヶ月前のIssueなので一応伺ったまでなので、あまりお気になさらず😀

こちらも論文投稿後で構いませんー

**Comment by aki2274** [comment]
#130 で解決したのでcloseします
