### ISSUE TITLE
BioCondaへの登録

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#85]
### As Is（今の状態を記載）

PyPIに登録していただきましたので、次はBioCondaへの登録をしましょう！

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

- [x] `conda install -c conda-forge -c bioconda konezumiaid`でインストールを可能とする。

BioCondaに登録すると、bowtieやbedtoolsのインストールをcondaで一括で行うことができ、より簡易で安全なインストールが可能となります。

### アクション（改善のための具体的なアクションを記載）

私は以下のようなスクリプトを使って、biocondaへの登録を半自動化しています

[upload-bioconda.sh.txt](https://github.com/user-attachments/files/15546460/upload-bioconda.sh.txt)

可読性は例によって低いので、ご一緒に確認できれば幸いです🙇

bowtieとbedtoolsは追記する必要がございます。  
以下のyamlのように、`requirements/run`に`bowtie`と`bedtools`を追加します

- https://github.com/bioconda/bioconda-recipes/blob/024a4ef3d3cf2a25f1fccae523aad51b2b473045/recipes/bacpage/meta.yaml#L29

### 課題 （現状分かっている課題を記載）

None?

**Comment by akikuno** [comment]
Licenseファイル（とhelpコマンド）を追加した新しいバージョンをPyPIに登録して、もういちど新しくPRを送ると良いかもしれませんー👀

もし新しくPRを送る場合には、以下のPRはいったんクローズしていただけますと幸いです🙇
https://github.com/bioconda/bioconda-recipes/pull/48312

**Comment by aki2274** [comment]
こちらいったんclose致しました。折を見てまたPRを送りたいと思います。

**Comment by akikuno** [comment]
#90 と相互リンクを貼っておきます

**Comment by akikuno** [comment]
@aki2274 

いまのv0.2.2なら登録できそうでしょうか？😄

**Comment by aki2274** [comment]
> 02:03:48 BIOCONDA INFO (OUT) konezumiaid 0.2.2 requires bedtools, which is not installed.
02:03:48 BIOCONDA INFO (OUT) konezumiaid 0.2.2 requires bowtie, which is not installed.
02:03:49 BIOCONDA INFO (OUT) WARNING: Tests failed for konezumiaid-0.2.2-pyhdfd78af_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
02:03:49 BIOCONDA INFO (OUT) TESTS FAILED: konezumiaid-0.2.2-pyhdfd78af_0.tar.bz2

で困ってます．biocondaのテスト環境でbedtoolsとbowtieのインストールができていないということですよね.
現状の[meta.yaml](https://github.com/bioconda/bioconda-recipes/pull/48692/files)で``` requires:```を指定しているつもりなのですがうまくいきません．どのように改善すればよいかご教示ください．

**Comment by aki2274** [comment]
commands:から -pip checkを除いちゃったんですがこれは何か問題ありますか？こうするとうまくいきそうな気がしたのですが...

**Comment by akikuno** [comment]
おおーおそらく、PyPIの環境を優先しているのでしょうか。

grayskullで、PyPIを参照せずにmeta.yamlをつくることができます。

```bash
grayskull pypi https://github.com/aki2274/KOnezumi-AID
```

いま、滝さんのReleaseはpre-releaseなので、これをlatestにしていただくと、meta.yamlをつくることができます。

![image](https://github.com/aki2274/KOnezumi-AID/assets/15861316/b50c1df7-e9ba-4f83-82b3-0d4054f8ede3)


そうすると、以下のyamlの9行目のようにsource:urlがpypiではなく、github.comになっているyamlが生成されると思います。そうすると、34魏行目で記載されているbedtoolsが実行できるのでは、と期待しています…

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/binny/meta.yaml

**Comment by akikuno** [comment]
おおーおそらく、PyPIの環境を優先しているのでしょうか。

grayskullで、PyPIを参照せずにmeta.yamlをつくることができます。

```bash
grayskull pypi https://github.com/aki2274/KOnezumi-AID
```

いま、滝さんのReleaseはpre-releaseなので、これをlatestにしていただくと、meta.yamlをつくることができます。

![image](https://github.com/aki2274/KOnezumi-AID/assets/15861316/b50c1df7-e9ba-4f83-82b3-0d4054f8ede3)


そうすると、以下のyamlの9行目のようにsource:urlがpypiではなく、github.comになっているyamlが生成されると思います。そうすると、34魏行目で記載されているbedtoolsが実行できるのでは、と期待しています…

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/binny/meta.yaml

**Comment by aki2274** [comment]
> commands:から -pip checkを除いちゃったんですがこれは何か問題ありますか？こうするとうまくいきそうな気がしたのですが...

これやっちゃうとうまくテスト通りました．latestにすることで解決できるのならばそちらのほうがよいですね．

**Comment by akikuno** [comment]
改めて、bedtoolsはpipでインストールできないので、`pip check`がエラーになるのは必然なのだから、削除してもよい気がしてきました！

**Comment by aki2274** [comment]
please review & mergeのラベルをもらうことができました．あとはマージ待ちです．

**Comment by aki2274** [comment]
無事マージされました！
```conda install -c conda-forge -c bioconda konezumiaid```を行うとSolving environmentが相当時間がかかっているので依存関係の指定で何らかの問題が起こってそうですかね😓

**Comment by akikuno** [comment]
おめでとうございますーーー🎊🎊🎊

`conda install -c conda-forge -c bioconda konezumiaid`について、私のPCでは48秒くらいでとくに遅いと感じませんでした😁

![image](https://github.com/aki2274/KOnezumi-AID/assets/15861316/6fa7522d-437f-4bb0-8a18-6898b1b48deb)

**Comment by akikuno** [comment]
@aki2274 
いままでkonezumiaidはpipで、bedtools/bowtieはcondaでと別途にインストールしていましたが、いま`conda install`で一括インストールが可能となりましたので、ぜひ、READMEのインストール方法について更新していただけますと幸いです！

**Comment by aki2274** [comment]
クリーンな環境で行っても時間がかかりますね．．．とりあえず久野先生側ではうまくいっていそうでよかったです．
原因がわかり次第改善しようと思います．とりあえずイシューはクローズします．

**Comment by aki2274** [comment]
こちらwslの環境で行っていないことが原因でした．wslでは問題なくインストールできました．

**Comment by akikuno** [comment]
READMEに以下を加筆・修正してくださいー

- 推奨環境 (WSL2, Linux, macOS) * macOSでは動きますかね？
- BioCondaによるInstallation
