### ISSUE TITLE
Zenodoの登録

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#88]
### As Is（今の状態を記載）

None

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

論文化の際にKOnezumi-AIDのDOI（Digital Object Identifier）が必要ですので、Zenodoの登録をお願いいたします🙇

登録が完了しますと各バージョンにおけるDOIが自動的に付与されます。

例えば、DAJIN2 v0.5.0のDOIは[10.5281/zenodo.11482234](https://doi.org/10.5281/zenodo.11482234)になります。

### アクション（改善のための具体的なアクションを記載）

以下が参考になるかと存じます

https://zenn.dev/nakamura196/articles/705d643489a794

**Comment by aki2274** [comment]
こちら登録いたしました。
次のリリースを行い、IDが付与されたことが確認され次第Closeさせていただきます。

**Comment by akikuno** [comment]
Zenodoの登録おめでとうございますー🎊

https://zenodo.org/records/12515265

**Comment by aki2274** [comment]
うまく発行されていました．こちら自動でreadmeに反映させるようなことを行ったほうがよいですよね．

**Comment by akikuno** [comment]
そうですね！

こんなかんじで、自動的に反映できるようです

https://gist.github.com/seignovert/ae6771f400ca464d294261f42900823a

https://zenn.dev/nakamura196/articles/705d643489a794#%E3%83%90%E3%83%83%E3%82%B8%E3%81%AE%E8%A1%A8%E7%A4%BA

**Comment by aki2274** [comment]
#94 でバッジを付けました．とりあえずはライセンスとzenodoです．

**Comment by aki2274** [comment]
登録，readmeへのバッチの表記ができたのでcloseします．
