### ISSUE TITLE
helpコマンド (`-h/--help`) の実装

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#90]
### As Is（今の状態を記載）

`konezumiaid -h`で`File not found`エラーになります

### To Be （理想の状態を記載。タスク完了の条件にもなる。）

`konezumiaid -h`、`konezumiaid --help`でヘルプメッセージが表示されるようにする

### アクション（改善のための具体的なアクションを記載）

`argparse`での引数受の取りが良いかと思います。

以下の公式ドキュメントが参考になると思います。

https://docs.python.org/ja/3/library/argparse.html#example

### 課題 （現状分かっている課題を記載）

None

**Comment by akikuno** [comment]
こちらができたら、 #85 も対応可能でしょうかねー😀

**Comment by aki2274** [comment]
コマンド登録できたのでcloseします．
