### ISSUE TITLE
READMEの加筆・修正

### ISSUE THREAD

**Issue by akikuno** [aki2274/KOnezumi-AID#95]
READMEに以下を加筆・修正してくださいー

- 推奨環境 (WSL2, Linux, macOS) * macOSでは動きますかね？
- BioCondaによるInstallation

_Originally posted by @akikuno in https://github.com/aki2274/KOnezumi-AID/issues/85#issuecomment-2189990236_

**Comment by akikuno** [comment]
> 推奨環境 (WSL2, Linux, macOS) 
こちらのご記載はございましたね。失礼しました。

macOS (Apple Sicilon)での動作確認はいかがいたしましょうか？
私の手持ちのM1 mac miniでよければ試しますー

**Comment by aki2274** [comment]
> macOS (Apple Sicilon)での動作確認はいかがいたしましょうか？
私の手持ちのM1 mac miniでよければ試しますー

macOSのマシンを持っていないので試していただければ幸いです

**Comment by akikuno** [comment]
#104 に記載したので、こちらはCloseしますー
