### ISSUE TITLE
pyproject.tomlの修正

### ISSUE THREAD

**Issue by aki2274** [aki2274/KOnezumi-AID#99]
PyPIを通してインストールする際に
pyproject.tomlに以下のような記述があると,bowtieとbedtoolsをpipインストールできなくてエラーが起こるような気がするのですがいかがでしょうか．poetryの依存関係はpipを通して解決するのだと考えていますがあっていますか？
```
[tool.poetry.dependencies]
python = "^3.9"
numpy = "1.26.0"  
pandas = "2.2.2"
primer3-py = "^2.0.1"
bedtools = "2.28.0"
bowtie = "1.1.2"
```

**Comment by akikuno** [comment]
そうですね、PyPIにあるパッケージをインストールするようあので、bedtoolsやbowtieは無理かと思います😅

https://python-poetry.org/docs/repositories/

bowtieについては全く違うパッケージをインストールしてしまう可能性がありますので、控えたほうが良さそうです。

https://pypi.org/project/bowtie/

**Comment by aki2274** [comment]
ご確認ありがとうございます。 #102 で削除しました．
